### ISSUE TITLE
Cambiar servidor de Sql Server por defecto

### ISSUE THREAD

**Issue by hbiarge** [DotNetters/cinematic.core#1]
Se podría cambiar el servidor de Sql Server por defecto para que no exija una instalación local de Sql Server. Con Visual Studio se instala LocalDb, que podría ser el servidor por defecto.

Cambiar *server=.* por *server=localdb\mssqlserver*

**Comment by Kash0321** [comment]
Hecho, pero con _server=localdb\mssqlserver_ no me ha funcionado, en mi equipo parece que la configuración de la instancia de LocalDB es esta: _server=(localdb)\\mssqllocaldb_ ¿Te parece correcto, o me he perdido algo?

Y otra cosilla, ya que estamos con las cadenas de conexión. Inicialmente lo puse en marcha con SQLite, y funcionaba perfectamente, de hecho hay código comentado con la versión para SQLite en la clase startup.cs y en el archivo appsettings.json, pero me di cuenta de que las migrations diferían ligeramente entre la versión para SQLite y la de SQLServer, en las columnas de tipo identidad, y no sé como mantener a la vez las dos versiones de las migrations. No estaría mal poder tener ambas, sobre todo para ejecutarlo en Linux sin tener que instalar SQL Server v.next. ¿Sabes si se podrían mantener las migrations para los dos sistemas de BD de una forma cómoda?
